name: Jest Unit Testing and Lint
run-name: ${{ github.actor }} has initiated a Pull Request
on: [push]
jobs:
  jest-unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm ci
              npm run build
              npm run test
              npm run lint