name: Jest Unit Testing and Lint
run-name: ${{ github.actor }} triggered a build by a ${{ github.event_name }} event.
on: 
  push:
  pull_request:
    branches:
      - master
jobs:
  jest-unit_test-lint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./testApp
    steps:
      - uses: actions/checkout@v3
      - run: |
              npm ci
              npm run build
              npm run test
              npm run lint
        working-directory: ${{env.working-directory}}